apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearting-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hearting-back
  template:
    metadata:
      labels:
        app: hearting-back
    spec:
      containers:
        - name: hearting-back
          image: youngmookk/hearting-backend
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hearting-back-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: hearting-back
spec:
  selector:
    app: hearting-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
