apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearting-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hearting-front
  template:
    metadata:
      labels:
        app: hearting-front
    spec:
      containers:
        - name: hearting-front
          image: youngmookk/hearting-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hearting-front
spec:
  selector:
    app: hearting-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
